In [4]:
#Instalação do ecommerce
import kagglehub

path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Downloading to C:\Users\Win10\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\2.archive...

100%|██████████| 42.6M/42.6M [00:04<00:00, 9.34MB/s]

Extracting files...

Path to dataset files: C:\Users\Win10\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/marketing-funnel-olist")

print("Path to dataset files:", path)

Downloading to C:\Users\Win10\.cache\kagglehub\datasets\olistbr\marketing-funnel-olist\2.archive...

100%|██████████| 278k/278k [00:00<00:00, 487kB/s]

Extracting files...
Path to dataset files: C:\Users\Win10\.cache\kagglehub\datasets\olistbr\marketing-funnel-olist\versions\2

In [6]:
import pandas as pd
df_funil = pd.read_csv('C:/Users/Win10/Documents/Documentos/keagle/olist_marketing_qualified_leads_dataset.csv',sep=',', encoding='latin-1')
df_conv = pd.read_csv('C:/Users/Win10/Documents/Documentos/keagle/olist_closed_deals_dataset.csv',sep=',', encoding='latin-1')
df_fat = pd.read_csv('C:/Users/Win10/Documents/Documentos/keagle/olist_order_items_dataset.csv',sep=',', encoding='latin-1')
df_an = pd.read_csv('C:/Users/Win10/Documents/Documentos/keagle/olist_orders_dataset.csv',sep=',', encoding='latin-1')

In [47]:
#Verificar informações do arquivo - Marketing

df_funil.info()
df_funil.describe()

#mql_id (sem duplicatas), datas ok(primeiro contato), landing_page_id (verificar), origem (verificar valores distintos)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mql_id              8000 non-null   object
 1   first_contact_date  8000 non-null   object
 2   landing_page_id     8000 non-null   object
 3   origin              7940 non-null   object
dtypes: object(4)
memory usage: 250.1+ KB

,mql_id,first_contact_date,landing_page_id,origin
count,8000,8000,8000,7940
unique,8000,336,495,10
top,dac32acd4db4c29c230538b72f8dd87d,2018-05-02,b76ef37428e6799c421989521c0e5077,organic_search
freq,1,93,912,2296

In [45]:
#Verificar informações do arquivo - Fechamento
df_conv.info()

df_conv.describe(exclude='number') 

#msql_id e seller possuem ids unicos
#Bussiness / lead_type / profile / average_stock / business_type Verificar valores únicos e contagem de nulos
#lead_behaviour_profile -- Alguns aparentam possuir mais de um perfil

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   mql_id                         842 non-null    object
 1   seller_id                      842 non-null    object
 2   sdr_id                         842 non-null    object
 3   sr_id                          842 non-null    object
 4   won_date                       842 non-null    object
 5   business_segment               841 non-null    object
 6   lead_type                      836 non-null    object
 7   lead_behaviour_profile         665 non-null    object
 8   has_company                    63 non-null     object
 9   has_gtin                       64 non-null     object
 10  average_stock                  66 non-null     object
 11  business_type                  832 non-null    object
 12  declared_product_catalog_size  69 non-null     float64
 13  declared_monthly_revenue       842 non-null    float64
dtypes: float64(2), object(12)
memory usage: 92.2+ KB

In [46]:
#Verificar informações do arquivo - Faturamento
df_fat.info()
df_fat.describe(exclude = 'number') 
#Verificar valores duplicados order_id

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

,order_id,product_id,seller_id,shipping_limit_date
count,112650,112650,112650,112650
unique,98666,32951,3095,93318
top,8272b63d03f5f79c56e9e4120aec44ef,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2017-07-21 18:25:23
freq,21,527,2033,21

In [28]:
#Verificar informações do arquivo - Pedidos
df_an.info()
df_an.describe(exclude='number') 

#Verificar valores únicos order_status, verificar se não há viagens no tempo (datas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [49]:
#Conexão com o banco de dados
!pip install sqlalchemy psycopg2

# Importando a ferramenta do motor
from sqlalchemy import create_engine

# 1. Configurando as credenciais
usuario = 'seu_usuario_aqui'
senha = 'sua_senha_aqui' 
host = 'seu_local_host'
porta = 'sua_porta'
banco = 'seu_banco' 

# 2. Montando a string de conexão
string_conexao = f"postgresql://{usuario}:{senha}@{host}:{porta}/{banco}"

# 3. Criando o motor de envio
engine = create_engine(string_conexao)

print("Motor de conexão criado com sucesso!")

Requirement already satisfied: sqlalchemy in c:\users\win10\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2 in c:\users\win10\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\win10\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\win10\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Motor de conexão criado com sucesso!

In [51]:
#Envio para o Banco

print("Iniciando a carga dos dados na camada Staging...")

# 1. Tabela de Leads (Topo do Funil)
df_funil.to_sql('tb_funil_marketing', con=engine, schema='staging', if_exists='replace', index=False)

# 2. Tabela de Conversão (Contratos Fechados)
df_conv.to_sql('tb_negocios_fechados', con=engine, schema='staging', if_exists='replace', index=False)

# 3. Tabela de Faturamento (Itens Vendidos)
df_fat.to_sql('tb_itens_faturados', con=engine, schema='staging', if_exists='replace', index=False)

# 4. Tabela de Status dos Pedidos (Filtro de Qualidade)
df_an.to_sql('tb_status_pedidos', con=engine, schema='staging', if_exists='replace', index=False)

print("Carga completa! Dados organizados no esquema 'staging'.")

Iniciando a carga dos dados na camada Staging...
Carga completa! Dados organizados no esquema 'staging'.